Vagrant.configure("2") do |config|
  config.vm.disk :disk, size: '128GB', primary: true
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |h|
    config.vm.synced_folder "../clulster", "/home/vagrant/cluster", type: "rsync"
    h.cpus = 10
    h.enable_virtualization_extensions = true
    h.enable_checkpoints = false
    h.vmname = "pipedrive"
    h.memory = 18 * 1024
  end
  config.vm.provider "virtualbox" do |v|
    config.vm.synced_folder "../cluster", "/home/vagrant/cluster"
    v.cpus = 10
    v.memory = 18 * 1024
    v.name = "pipedrive"
    v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  end
  config.vm.provision :shell, path: "provision.sh"
end
