---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: registry
  name: registry-headless
spec:
  clusterIP: None
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  publishNotReadyAddresses: true
  selector:
    app: registry
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: {{ include "serviceName" . | quote }}
spec:
  ports:
    - port: {{ include "servicePort" . }}
      protocol: TCP
      targetPort: 5000
  selector:
    app: registry
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls
type: kubernetes.io/tls
data:
  tls.key: |
    {{- include "tlsKeyPem" . | nindent 4 }}
  tls.crt: |
    {{- include "tlsCrtPem" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  podManagementPolicy: Parallel
  replicas: {{ include "replicasCount" . }}
  selector:
    matchLabels:
      app: registry
  serviceName: registry-headless
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: {{ include "imageUrl" . | quote }}
          name: registry
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /run/secrets/registry-tls/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /run/secrets/registry-tls/tls.key
          ports:
            - containerPort: 5000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5000
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 250m
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-vol
            - mountPath: /run/secrets/registry-tls
              name: registry-tls
      volumes:
        - name: registry-tls
          secret:
            defaultMode: {{ "0600" | toDecimal }}
            secretName: registry-tls
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: registry-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        storageClassName: {{ include "storageClassName" . | quote }}