def GBasMB(numGB)
  1024 * numGB
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.disk :disk, size: "64GB", primary: true

  config.vm.provider "virtualbox" do |vbox|
    vbox.cpus = 6
    vbox.memory = GBasMB 16
  end

  (0..0).each do |n|
    name = "node#{n}"
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: "192.168.0.#{10+n}"
      node.vm.provider "virtualbox" do |vbox|
        vbox.name = name
      end
    end
  end

  config.vm.provision :file, source: "ca.pem", destination: "ca.pem"
  config.vm.provision :shell, path: "provision.sh"
end
