---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: kibana
  name: kibana-headless
spec:
  clusterIP: None
  ports:
    - port: 5601
      protocol: TCP
      targetPort: 5601
  publishNotReadyAddresses: true
  selector:
    app: kibana
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: {{ include "serviceName" . | quote }}
spec:
  ports:
    - port: {{ include "servicePort" . }}
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
spec:
  podManagementPolicy: Parallel
  replicas: {{ include "replicasCount" . }}
  selector:
    matchLabels:
      app: kibana
  serviceName: kibana-headless
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: {{ include "imageUrl" . | quote }}
          name: kibana
          ports:
            - containerPort: 5601
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          volumeMounts:
            - mountPath: /var/lib/kibana
              name: kibana-data
      securityContext:
        fsGroup: 106
        runAsGroup: 106
        runAsUser: 105
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: kibana-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        storageClassName: {{ include "storageClassName" . | quote }}